            - name: Prettier Code Formatting
  # You may pin to the exact commit or the version.
  # uses: permafrost-dev/prettier-docker-ga@259e09f952187003c6f4c14e10c3f1a8d17ba715
  uses: permafrost-dev/prettier-docker-ga@v1.0.5
          
